### ISSUE TITLE
onClick not working

### ISSUE THREAD

**Issue by leocavalcante** [mariposa-dart/mariposa#12]
A very simple app like:

```dart
import 'dart:html' show querySelector;

import 'package:mariposa/dom.dart';
import 'package:mariposa/mariposa.dart';

class App extends Widget {
  @override
  Node render() {
    return Button(
      onClick: (_) => print('Clicked'),
      child: Text('Click me'),
    );
  }
}

void main() {
  render(App(), querySelector('#app'));
}
```
Using:
```yaml
name: hello_mariposa

dependencies:
  mariposa: ^1.1.0-alpha.3

dev_dependencies:
  build_runner:
  build_web_compilers:
```

Shows the button, but clicking on it doesn't prints "Clicked", not erros too.
